import PenOne from "../assets/penOne.png";
import PenTwo from "../assets/penTwo.png";
import PenThree from "../assets/penThree.png";
import PenFour from "../assets/penFour.png";
import PenFive from "../assets/penFive.jpg";
import PenSix from "../assets/penSix.png";

export const GraphDataTimeline = [
  {
    transactionType: "BUY",
    token: "#1523",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: "None",
    transactionValue: 2,
    createdAt: "2022-03-29T19:59:41.072Z",
    profit: -1,
    rarityRank: 142,
    listingPrice: 2,
  },
  {
    transactionType: "BUY",
    token: "#1524",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenOne,
    transactionValue: 0.2,
    createdAt: "2022-04-03T19:59:41.072Z",
    profit: 0,
    rarityRank: 102,
    listingPrice: 2,
  },
  {
    transactionType: "SELL",
    token: "#1525",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenTwo,
    transactionValue: 2,
    createdAt: "2022-04-29T19:59:41.072Z",
    profit: 3.8,
    rarityRank: 152,
    listingPrice: 2,
  },
  {
    transactionType: "BUY",
    token: "#1526",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenThree,
    transactionValue: 2,
    createdAt: "2022-05-15T19:59:41.072Z",
    profit: 1.8,
    rarityRank: 92,
    listingPrice: 2,
  },
  {
    transactionType: "MINT",
    token: "#1527",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenFour,
    transactionValue: 0.8,
    createdAt: "2022-05-29T19:59:41.072Z",
    profit: 1,
    rarityRank: 70,
    listingPrice: 0.8,
  },
  {
    transactionType: "SELL",
    token: "#1528",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenFive,
    transactionValue: 2,
    createdAt: "2022-06-25T19:59:41.072Z",
    profit: 3,
    rarityRank: 80,
    listingPrice: 2,
  },
  {
    transactionType: "SELL",
    token: "#1529",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: PenSix,
    transactionValue: 1,
    createdAt: "2022-07-14T19:59:41.072Z",
    profit: 4,
    rarityRank: 10,
    listingPrice: 1,
  },
  {
    transactionType: "SELL",
    token: "#1530",
    collectionSlug: "azuki",
    collectionName: "Azuki",
    assetThumbnailUrl: "none",
    transactionValue: 0.2,
    createdAt: "2022-07-29T19:59:41.072Z",
    profit: 4.2,
    rarityRank: 95,
    listingPrice: 0.2,
  },
];
